#!/usr/bin/env python

Import("env")

env.servers_sources = []

env.add_source_files(env.servers_sources, "display_server.cpp")
env.add_source_files(env.servers_sources, "register_server_types.cpp")
env.add_source_files(env.servers_sources, "rendering_server.cpp")
env.add_source_files(env.servers_sources, "text_server.cpp")

SConscript("debugger/SCsub")
SConscript("display/SCsub")
SConscript("rendering/SCsub")
SConscript("text/SCsub")

lib = env.add_library("servers", env.servers_sources)

env.Prepend(LIBS=[lib])
